config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    collection do
      get 'create', as: :create
    end
    resources :likes
  end
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :user, scope: :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]
  before_action :set_post

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = @post.likes.new(user: current_user)

    respond_to do |format|
      if @like.save
        format.js { }
      else
        format.js { }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url, notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      params.require(:like).permit(:post_id, :user_id)
    end

    def set_post
      @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @qiniu_upload_token = generate_qiniu_upload_token
    @post = Post.new

  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
   upload_ret = JSON.parse(Base64.urlsafe_decode64(params[:upload_ret]))
   @post = Post.new(
   title: upload_ret['title'],
   filename: upload_ret['fname'],
   qiniu_hash: upload_ret['hash'],
   creator: current_user,
   )

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :filename, :qiniu_hash)
    end

    def generate_qiniu_upload_token
       put_policy = Qiniu::Auth::PutPolicy.new('pic-share')
       put_policy.return_body = {
       fname: '$(fname)',
       hash: '$(etag)',
       title: '$(x:title)'
       }.to_json
       put_policy.return_url = create_posts_url
       Qiniu::Auth.generate_uptoken(put_policy)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def qiniu_image_url(post, format = :raw)
   url = "http://oi0kyjmmk.bkt.clouddn.com/#{post.qiniu_hash}"
   
   case format
   when :square
   url << '?imageView2/1/w/300/h/300/q/90'
   when :preview
   url << '?imageView2/2/w/1000/h/1000/q/90'
   when :raw
   url << "?attname=#{post.filename}"
   else
   url
   end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PicShare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if user_signed_in? %>
      <p>
        Hello, <%= current_user.email %>,
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      </p>
      <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_for(like) do |f| %>
  <% if like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %>
    <%= f.text_field :post_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/create.js.erb
$("#<%= "post_#{@post.id}_likes" %>").text("<%= "#{@post.likes.count} likes" %>")

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Likes</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.post %></td>
        <td><%= like.user %></td>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @like.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @like.user %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>

app/views/posts/_form.html.erb
<%= form_tag 'http://upload.qiniu.com', multipart: true do %>
 <%= hidden_field_tag :token, @qiniu_upload_token %>
 
 <div class="field">
 <%= label_tag :title %><br>
 <%= text_field_tag 'x:title' %>
 </div>
 <div class="field">
 <%= label_tag :image %><br>
 <%= file_field_tag :file %>
 </div>
 <div class="actions">
 <%= submit_tag 'Create' %>
 </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<div class="posts">
 <% @posts.each do |post| %>
     <%= link_to image_tag(qiniu_image_url(post, :square), size: '300'), post, class: 'image' %>
     <br>
     <%= post.title %>
     <br>
     <%= content_tag(:span, "#{post.likes.count} likes", id: "post_#{post.id}_likes") %>
     <% if user_signed_in? %>
       <br>
       <%= link_to 'Like', post_likes_path(post), method: :post, remote: true %>
       <% if(post.creator == current_user) %>
         <br>
         <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
       <% end %>
     <% end %>
  <% end %>
</div>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
 <%= link_to image_tag(qiniu_image_url(@post, :preview)), '#', class: 'image' %>
</p>
 
<%= link_to 'Back', posts_path %>